# Generated by Django 5.0.1 on 2024-01-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Premium', 'premium'), ('Standard', 'standard'), ('free', 'free')], default='free', max_length=40),
        ),
    ]
