# Generated by Django 5.0.1 on 2024-01-28 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_alter_membership_membership_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
