# Generated by Django 5.0.1 on 2024-01-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_alter_membership_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Premium', 'prm'), ('Standard', 'std'), ('free', 'free')], default='free', max_length=40),
        ),
        migrations.AlterField(
            model_name='membership',
            name='slug',
            field=models.SlugField(),
        ),
    ]
