# Generated by Django 5.0.1 on 2024-01-29 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_alter_membership_membership_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount',
            new_name='price',
        ),
    ]
