# Generated by Django 5.0.1 on 2024-02-07 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_rename_amount_payment_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='membership.membership'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='membership.usermembership'),
        ),
    ]
