# Generated by Django 5.0.1 on 2024-02-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0007_payment_membership_payment_user_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('premium', 'prm'), ('standard', 'std'), ('free', 'free')], default='free', max_length=40),
        ),
    ]
