# Generated by Django 5.0.1 on 2024-02-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0008_alter_membership_membership_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='next_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
