# Generated by Django 5.0.1 on 2024-01-25 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='videos/')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contentpd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('position', models.IntegerField()),
                ('thumbnails', models.ImageField(upload_to='')),
                ('pdf_file', models.FileField(upload_to='pdfs/')),
                ('allowed_memberships', models.ManyToManyField(to='membership.membership')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('position', models.IntegerField()),
                ('video_url', models.CharField(max_length=200, unique=True)),
                ('thumbnails', models.ImageField(upload_to='')),
                ('allowed_memberships', models.ManyToManyField(to='membership.membership')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.video')),
            ],
        ),
    ]
