# Generated by Django 5.0.1 on 2024-01-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_video_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpd',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
