# Generated by Django 5.0.1 on 2024-01-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_playvideo_remove_video_video_file_video_playvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='playvideo',
        ),
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(null=True, upload_to='video/%Y'),
        ),
        migrations.DeleteModel(
            name='PlayVideo',
        ),
    ]
