# Generated by Django 5.0.1 on 2024-01-31 21:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_remove_video_playvideo_video_video_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentpd',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='contentpd',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
