# Generated by Django 5.0.1 on 2024-02-01 00:45

import django.db.models.deletion
import django.utils.timezone
import embed_video.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_contentpd_options_alter_video_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='thumbnails',
        ),
        migrations.RemoveField(
            model_name='content',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='contentpd',
            name='thumbnails',
        ),
        migrations.AddField(
            model_name='content',
            name='linked_video',
            field=embed_video.fields.EmbedVideoField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='pdf_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.contentpd'),
        ),
    ]
