# Generated by Django 5.0.1 on 2024-02-02 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_remove_content_thumbnails_remove_content_video_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='linked_video',
            new_name='video_url',
        ),
    ]
